name: Fetch

on:
  workflow_dispatch:
  schedule:
    # 表达式生成  https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    - cron: '0 0,*/1,* * * *'

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
    - name: 迁出代码
      uses: actions/checkout@v2
    - name: 安装Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: 设置时区
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
    - name: 安装依赖
      run: |
        pip install requests
        pip install beautifulsoup4
    - name: 执行任务
      run: |
        python ./Free/fetch.py
        python ./Free/freenode.py
      
    - name: 提交更改
      run: |                 
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git pull origin master
        git add -A
        git commit -m "$(date '+%Y-%m-%d %H:%M:%S')抓取节点"
    - name: 推送更改
      uses: ad-m/github-push-action@master
      with:
        branch: master
